id: 4b09fe49921b429298c0d991e48fcb36
initial_creation_type: ocr
source_metadata:
  volumes:
    e7c3f4c977b2418baf4dc2a7292148be:
      base_file: v056.txt
      image_group_id: I1PD95902
      title: ''
      total_pages: 1605
      volume_number: 57
